# Generated by Django 3.2.13 on 2022-07-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBO', '0003_fig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fig',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
